import { createContext, useContext, useEffect, useState } from 'react'

const STORAGE_KEY = 'compass_language'

const TRANSLATIONS = {
  en: {
    dir: 'ltr',
    nav_home: 'Home',
    nav_about: 'About',
    nav_pricing: 'Pricing',
    nav_dashboard: 'Dashboard',
    nav_alerts: 'Alerts Center',
    nav_statements: 'Statements',
    nav_portfolio: 'Portfolio',
    nav_settings: 'Account Settings',
    nav_insights: 'Insights',
    nav_login: 'Login',
    nav_register: 'Register',
    footer_about: 'About',
    footer_privacy: 'Privacy',
    footer_terms: 'Terms',
    footer_contact: 'Contact',
    footer_copyright: 'All rights reserved.',

    // Privacy Page
    privacy_title: 'Privacy Policy',
    privacy_subtitle: 'How we collect, use, and protect your personal information.',
    privacy_collect_title: 'Information We Collect',
    privacy_collect_body: 'We collect information you provide directly to us, such as your name, email address, and financial account data you choose to upload. We also collect usage data automatically, including log data, device information, and cookies.',
    privacy_use_title: 'How We Use Your Information',
    privacy_use_body: 'We use the information we collect to provide, maintain, and improve our services, process transactions, send transactional and promotional communications, and comply with legal obligations.',
    privacy_share_title: 'Information Sharing',
    privacy_share_body: 'We do not sell your personal information. We may share information with third-party service providers who assist us in operating our platform, subject to confidentiality agreements. We may also disclose information when required by law.',
    privacy_security_title: 'Data Security',
    privacy_security_body: 'We implement industry-standard security measures including encryption in transit and at rest, access controls, and regular security audits. However, no method of transmission over the Internet is 100% secure.',
    privacy_contact_title: 'Contact Us',
    privacy_contact_body: 'If you have questions about this Privacy Policy, please contact us at privacy@compass-finance.app.',
    privacy_updated: 'Last updated: January 1, 2026',

    // Terms Page
    terms_title: 'Terms of Service',
    terms_subtitle: 'Please read these terms carefully before using Compass.',
    terms_acceptance_title: 'Acceptance of Terms',
    terms_acceptance_body: 'By accessing or using Compass, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree to these terms, please do not use our service.',
    terms_use_title: 'Use of Service',
    terms_use_body: 'Compass is a personal finance management platform. You may use our service only for lawful purposes and in accordance with these Terms. You agree not to misuse the service or help anyone else do so.',
    terms_account_title: 'Your Account',
    terms_account_body: 'You are responsible for safeguarding your account credentials and for all activity that occurs under your account. You must notify us immediately of any unauthorized use of your account.',
    terms_liability_title: 'Limitation of Liability',
    terms_liability_body: 'Compass provides financial data aggregation and analysis tools for informational purposes only. We are not a licensed financial advisor. Our service is provided "as is" without warranties of any kind. We shall not be liable for any indirect, incidental, or consequential damages.',
    terms_changes_title: 'Changes to Terms',
    terms_changes_body: 'We reserve the right to modify these Terms at any time. We will notify you of significant changes via email or through our platform. Continued use of the service after changes constitutes acceptance of the new Terms.',
    terms_updated: 'Last updated: January 1, 2026',

    // Contact Page
    contact_title: 'Contact Us',
    contact_subtitle: 'Have a question or need help? We\'d love to hear from you.',
    contact_email_label: 'Email',
    contact_hours_label: 'Support Hours',
    contact_hours_value: 'Sunday – Thursday, 9:00–18:00',
    contact_location_label: 'Location',
    contact_name_label: 'Full Name',
    contact_name_placeholder: 'Your name',
    contact_email_field_label: 'Email Address',
    contact_email_placeholder: 'you@example.com',
    contact_message_label: 'Message',
    contact_message_placeholder: 'How can we help you?',
    contact_submit: 'Send Message',
    contact_success_title: 'Message Sent!',
    contact_success_body: 'Thank you for reaching out. We\'ll get back to you within 1–2 business days.',

    // User Menu
    usermenu_profile: 'Profile',
    usermenu_settings: 'Settings',
    usermenu_help: 'Help & Support',
    usermenu_signout: 'Sign out',
    usermenu_pro: 'Pro Member',
    usermenu_free: 'Free Tier',
    usermenu_aria: 'User menu',

    // Landing Page
    landing_title: 'Know exactly where your money goes.',
    landing_subtitle: 'Upload your bank statement and get instant AI-powered clarity on your spending — no bank connection required.',
    landing_get_started: 'Get Started Free',
    landing_login: 'Login to Dashboard',
    landing_stat_1_value: '10,000+',
    landing_stat_1_label: 'Transactions analyzed',
    landing_stat_2_value: '95%',
    landing_stat_2_label: 'Categorization accuracy',
    landing_stat_3_value: '< 2 min',
    landing_stat_3_label: 'Time to first insight',
    landing_how_title: 'How it works',
    landing_how_1_title: 'Upload your statement',
    landing_how_1_body: 'Export a PDF from your bank and upload it. No account linking, no credentials shared.',
    landing_how_2_title: 'AI extracts everything',
    landing_how_2_body: 'Our AI reads and categorizes every transaction — merchant, amount, date, and type — automatically.',
    landing_how_3_title: 'Get instant insights',
    landing_how_3_body: 'See your spending trends, smart alerts, and a full breakdown by category — right away.',
    landing_features_title: 'Everything you need',
    landing_feat_1_title: 'Smart Dashboard',
    landing_feat_1_body: 'Track your total balance, savings rate, and monthly expenses with live KPI cards and trend charts.',
    landing_feat_2_title: 'Proactive Alerts',
    landing_feat_2_body: 'Get notified about unusual charges, duplicate payments, and optimization opportunities before they cost you.',
    landing_feat_3_title: 'Deep Insights',
    landing_feat_3_body: 'AI-powered spending breakdown by category, 6-month trends, and your top spending habits — Pro tier.',
    landing_pricing_title: 'Simple, transparent pricing',
    landing_pricing_free_name: 'Free',
    landing_pricing_free_price: '₪0',
    landing_pricing_free_desc: 'Perfect to get started',
    landing_pricing_free_f1: '1 bank account',
    landing_pricing_free_f2: '3 statement uploads',
    landing_pricing_free_f3: 'Dashboard & alerts',
    landing_pricing_pro_name: 'Pro',
    landing_pricing_pro_price: '₪39.90',
    landing_pricing_pro_period: '/ month',
    landing_pricing_pro_desc: 'For serious financial clarity',
    landing_pricing_pro_f1: 'Unlimited accounts',
    landing_pricing_pro_f2: 'Unlimited uploads',
    landing_pricing_pro_f3: 'AI Insights & trends',
    landing_pricing_pro_f4: 'Priority support',
    landing_pricing_see_all: 'See full pricing →',
    landing_cta_title: 'Ready to take control of your finances?',
    landing_cta_subtitle: 'Join thousands of users who finally understand their spending.',
    landing_cta_button: 'Get Started Free',

    // Not Found Page
    notfound_title: 'Page Not Found',
    notfound_subtitle: "The page you are looking for doesn't exist or has been moved.",
    notfound_return_home: 'Return Home',

    // Login Page
    login_heading: 'Welcome back',
    login_subheading: 'Log in to securely manage your portfolio.',
    login_google_redirecting: 'Redirecting…',
    login_google_continue: 'Continue with Google',
    login_or_email: 'or email',
    login_email_label: 'Email address',
    login_password_label: 'Password',
    login_forgot_password: 'Forgot password?',
    login_signing_in: 'Signing in…',
    login_sign_in: 'Sign In',
    login_no_account: "Don't have an account?",
    login_sign_up: 'Sign up',
    login_fill_all_fields: 'Please fill in all fields.',
    login_failed: 'Failed to sign in. Check credentials.',
    login_google_failed: 'Failed to sign in with Google.',
    trust_encrypted_connection: 'Encrypted Connection',
    trust_secure_architecture: 'Secure Architecture',
    trust_enterprise_grade: 'Enterprise Grade',

    // Register Page
    register_heading: 'Create your account',
    register_subheading: 'Start automating your financial intelligence.',
    register_google_signup: 'Sign up with Google',
    register_full_name_label: 'Full Name',
    register_email_label: 'Email address',
    register_password_label: 'Password',
    register_confirm_password_label: 'Confirm Password',
    register_creating_account: 'Creating account…',
    register_create_account: 'Create Account',
    register_have_account: 'Already have an account?',
    register_log_in: 'Log in',
    register_fill_all_fields: 'Please fill in all fields.',
    register_passwords_mismatch: 'Passwords do not match.',
    register_failed: 'Failed to create account. Check if Supabase keys are configured.',
    register_google_failed: 'Failed to sign up with Google.',
    register_email_confirm_required: 'Account created! Please check your email to verify your account before logging in.',

    // Forgot Password Page
    forgot_heading: 'Forgot password?',
    forgot_subheading: "Enter your email and we'll send you a reset link.",
    forgot_check_inbox: 'Check your inbox — a reset link has been sent to',
    forgot_back_to_signin: 'Back to Sign In',
    forgot_email_label: 'Email address',
    forgot_sending: 'Sending…',
    forgot_send_reset_link: 'Send Reset Link',
    forgot_enter_email: 'Please enter your email address.',
    forgot_send_failed: 'Failed to send reset link.',

    // Dashboard sections
    dashboard_welcome_back: 'Welcome Back',
    dashboard_summary: "Here's a summary of your financial momentum.",
    dashboard_last_updated: 'Last Updated',
    kpi_total_balance: 'Total Balance',
    kpi_total_balance_tip: 'The combined balance across all your linked accounts. The % shows the weighted average growth rate across accounts.',
    kpi_savings: 'Savings',
    kpi_savings_tip: 'Total balance in accounts marked as Savings type.',
    kpi_monthly_expenses: 'Monthly Expenses',
    kpi_monthly_expenses_tip: 'Total debit transactions in the current calendar month. The % compares to last month.',
    quick_actions_title: 'Quick Actions',
    quick_action_upload_statement: 'Upload Statement',
    quick_action_view_transactions: 'View Transactions',
    quick_action_alerts_center: 'Alerts Center',
    quick_action_drop_zone: 'Drag & drop documents here',
    recent_tx_title: 'Recent Transactions',
    recent_tx_filter: 'Filter',
    recent_tx_more_options: 'More options',
    recent_tx_col_transaction: 'Transaction',
    recent_tx_col_date: 'Date',
    recent_tx_col_status: 'Status',
    recent_tx_col_amount: 'Amount',
    recent_tx_none: 'No recent transactions',
    tx_status_completed: 'Completed',
    tx_status_pending: 'Pending',
    tx_status_failed: 'Failed',
    chart_spending_trends: 'Spending Trends',
    chart_view_details: 'View Details',
    chart_empty_state: 'No spending data yet. Upload a statement to see your trends here.',
    chart_subtitle: 'Monthly spending',
    chart_total_label: 'Total',
    chart_months: 'months',
    chart_monthly_avg: 'Monthly avg',
    chart_peak_month: 'Peak month',
    chart_legend_current: 'Current month',
    chart_legend_above: 'Above average',
    chart_legend_below: 'Below average',

    // Month abbreviations
    month_jan: 'Jan', month_feb: 'Feb', month_mar: 'Mar', month_apr: 'Apr',
    month_may: 'May', month_jun: 'Jun', month_jul: 'Jul', month_aug: 'Aug',
    month_sep: 'Sep', month_oct: 'Oct', month_nov: 'Nov', month_dec: 'Dec',

    // Category names
    cat_bills_utilities: 'Bills & Utilities',
    cat_food_dining: 'Food & Dining',
    cat_shopping: 'Shopping',
    cat_transportation: 'Transportation',
    cat_health: 'Health',
    cat_entertainment: 'Entertainment',
    cat_electronics: 'Electronics',
    cat_other: 'Other',
    cat_uncategorized: 'Uncategorized',

    // Transactions Page
    tx_page_title: 'Transactions',
    tx_page_total: 'transactions total',
    tx_search_placeholder: 'Search by merchant or category…',
    tx_filter_all: 'All',
    tx_filter_expenses: 'Expenses',
    tx_filter_income: 'Income',
    tx_load_failed: 'Failed to load transactions',
    tx_no_match: 'No transactions match your filter.',

    // Alerts Page
    alerts_page_title: 'Alerts Center',
    alerts_page_subtitle: 'Monitor and manage critical account notifications, optimization opportunities, and security events requiring your attention.',
    alerts_system_status: 'System Status:',
    alerts_status_optimal: 'Optimal',
    alerts_stat_new: 'New Alerts',
    alerts_stat_new_attention: 'need attention',
    alerts_stat_all_clear: 'All clear',
    alerts_stat_in_progress: 'In Progress',
    alerts_stat_pending_resolution: 'Pending resolution',
    alerts_stat_saved: 'Saved for Later',
    alerts_stat_archived: 'Archived tasks',
    alerts_stat_value_impact: 'Est. Value Impact',
    alerts_stat_from_optimization: 'From optimization alerts',
    alerts_filter_all: 'All Alerts',
    alerts_filter_critical: 'Critical',
    alerts_filter_opportunities: 'Opportunities',
    alerts_filter_duplicates: 'Duplicates',
    alerts_sort_by_priority: 'Sort by: Priority',
    alerts_review: 'Review',
    alerts_dismiss: 'Dismiss',
    alerts_dismiss_aria: 'Dismiss alert',
    alerts_none_in_category: 'No alerts in this category.',
    pagination_previous: 'Previous page',
    pagination_next: 'Next page',

    // Upload Page
    upload_page_title: 'Secure Upload',
    upload_page_subtitle: 'Submit your financial documents for secure AI processing and storage.',
    upload_cancel: 'Cancel Upload',
    upload_step_choose_type: 'Choose Type',
    upload_step_upload_file: 'Upload File',
    upload_step_preview: 'Preview',
    upload_step_review_save: 'Review & Save',
    upload_no_accounts: "You don't have any accounts yet. Add one to continue.",
    upload_institution_label: 'Financial Institution',
    upload_select_institution: 'Select institution…',
    upload_account_name_label: 'Account Name',
    upload_account_name_placeholder: 'e.g. Personal Checking',
    upload_account_type_label: 'Account Type',
    upload_adding: 'Adding…',
    upload_add_account: 'Add Account',
    upload_account_label: 'Account',
    upload_select_account: 'Select account…',
    upload_doc_type_label: '1. Document Type',
    doc_type_bank_title: 'Bank Statement',
    doc_type_bank_desc: 'Monthly account summaries',
    doc_type_tax_title: 'Tax Document',
    doc_type_tax_desc: 'W-2, 1099, or returns',
    doc_type_invoice_title: 'Invoice',
    doc_type_invoice_desc: 'Vendor or client bills',
    doc_type_other_title: 'Other',
    doc_type_other_desc: 'Contracts and notices',
    upload_file_label: '3. File Upload',
    upload_drag_drop: 'Drag & drop your file here',
    upload_or_browse: 'or click to browse from your computer',
    upload_click_replace: 'Click to replace',
    upload_max_size: 'Max 50MB',
    upload_parsing_pdf: 'Parsing PDF…',
    upload_no_tx_found: 'No transactions found in this PDF. The format may not be supported yet.',
    upload_parse_failed: 'Failed to parse PDF:',
    upload_parsed_tx_title: 'Parsed Transactions',
    upload_selected_for_import: 'of {total} selected for import',
    upload_col_date: 'Date',
    upload_col_description: 'Description',
    upload_col_category: 'Category',
    upload_col_amount: 'Amount',
    upload_import_failed: 'Import Failed',
    upload_import_complete: 'Import Complete',
    upload_imported_success: 'transaction(s) imported successfully.',
    upload_duplicates_skipped: 'duplicate(s) were skipped.',
    upload_view_transactions: 'View Transactions',
    upload_tips_title: 'AI Extraction Tips',
    upload_tips_intro: 'Our Compass AI automatically extracts transactional data. Follow these guidelines for perfect accuracy.',
    upload_tip_1: 'Ensure all document pages are included in a single file.',
    upload_tip_2: 'Scans must be flat, well-lit, and legible without cropping.',
    upload_tip_3: 'Remove password protection from PDFs before uploading.',
    upload_encrypted_transfer: 'End-to-end encrypted transfer',
    upload_cancel_action: 'Cancel',
    upload_continue_to_review: 'Continue to Review',
    upload_parse_pdf: 'Parse PDF',
    upload_saving: 'Saving…',
    upload_import_n_transactions: 'Import {count} Transactions',
    upload_institution_select_label: '2. Financial Institution',
    upload_select_institution_placeholder: 'Select an institution...',
    upload_parsing_csv: 'Reading file…',
    upload_parse_csv: 'Continue to Column Mapping',
    upload_map_columns: 'Confirm Mapping',
    upload_step_map_columns: 'Map Columns',
    upload_no_tx_found_csv: 'No valid rows found after applying the column mapping. Please check your column assignments.',

    // Upload method selector
    upload_method_label: 'Import Method',
    upload_method_pdf_title: 'PDF Statement',
    upload_method_pdf_desc: 'Bank or credit card PDF export',
    upload_method_csv_title: 'CSV / Excel',
    upload_method_csv_desc: 'Spreadsheet export from your bank',

    // CSV column mapper
    csv_map_title: 'Map Your Columns',
    csv_map_subtitle: 'Tell us which column in your file matches each Compass field. We\'ve made our best guess — adjust if needed.',
    csv_map_missing_fields: 'Still missing required fields',
    csv_map_col_your_column: 'Your Column',
    csv_map_col_sample: 'Sample Data',
    csv_map_col_maps_to: 'Maps To',
    csv_map_skip: '— Skip this column —',
    csv_field_date: 'Date',
    csv_field_amount: 'Amount',
    csv_field_description: 'Description',
    csv_field_direction: 'Direction (optional)',

    // Insights Page
    insights_title: 'Insights',
    insights_subtitle: 'A breakdown of your spending patterns.',
    insights_total_spent: 'Total Spent',
    insights_transactions_count: 'transactions',
    insights_total_income: 'Total Income',
    insights_avg_transaction: 'Avg. Transaction',
    insights_top_category: 'Top Category',
    insights_spending_by_category: 'Spending by Category',

    // Profile Page
    profile_title: 'Profile',
    profile_subtitle: 'Manage your personal information.',
    profile_display_name_label: 'Display name',
    profile_display_name_placeholder: 'Your full name',
    profile_first_name_label: 'First name',
    profile_first_name_placeholder: 'First name only',
    profile_email_label: 'Email',
    profile_save_success: 'Profile saved successfully.',
    profile_save_failed: 'Failed to save profile.',
    profile_saving: 'Saving…',
    profile_save_changes: 'Save Changes',
    profile_tier_free: 'Free',

    // Settings Page
    settings_title: 'Settings',
    settings_subtitle: 'Manage your account preferences and security.',
    settings_section_display: 'Display',
    settings_currency_label: 'Currency',
    settings_currency_desc: 'Choose how amounts are displayed across the app.',
    settings_section_notifications: 'Notifications',
    settings_email_alerts_label: 'Email alerts',
    settings_email_alerts_desc: 'Receive transaction and alert summaries by email.',
    settings_push_alerts_label: 'Push notifications',
    settings_push_alerts_desc: 'Get real-time alerts on your device.',
    settings_section_security: 'Security',
    settings_new_password_label: 'New password',
    settings_confirm_password_label: 'Confirm new password',
    settings_password_updated: 'Password updated successfully.',
    settings_updating: 'Updating…',
    settings_update_password: 'Update Password',
    settings_passwords_mismatch: 'Passwords do not match.',
    settings_password_too_short: 'Password must be at least 8 characters.',
    settings_password_update_failed: 'Failed to update password.',
    settings_section_danger: 'Danger Zone',
    settings_delete_account_label: 'Delete account',
    settings_delete_account_desc: 'Permanently delete your Compass account and all associated data. This cannot be undone.',
    settings_delete_account_btn: 'Delete Account',
    settings_delete_modal_title: 'Delete Account',
    settings_delete_modal_body: 'This action is permanent. All your data will be deleted and cannot be recovered. Please contact support to proceed with account deletion.',
    settings_cancel: 'Cancel',

    // Pricing Page
    pricing_title: 'Simple, transparent pricing',
    pricing_subtitle: 'Start for free, upgrade when you need more.',
    pricing_most_popular: 'Most Popular',
    pricing_free_name: 'Free',
    pricing_free_feature_1: 'Up to 2 connected accounts',
    pricing_free_feature_2: '5 statement uploads per month',
    pricing_free_feature_3: 'Basic alerts (unusual charges, duplicates)',
    pricing_free_feature_4: 'Dashboard KPIs & spending trends',
    pricing_free_cta: 'Get Started',
    pricing_pro_name: 'Compass Pro',
    pricing_pro_feature_1: 'Unlimited accounts & statement uploads',
    pricing_pro_feature_2: 'Yield Optimization alerts',
    pricing_pro_feature_3: 'Custom category creation',
    pricing_pro_feature_4: 'Merchant merge for duplicate detection',
    pricing_pro_feature_5: 'Advanced analytics & insights',
    pricing_pro_cta: 'Upgrade to Pro',
    pricing_period_month: '/ month',
    pricing_faq_title: 'Frequently asked questions',
    pricing_faq_q1: 'Can I switch plans later?',
    pricing_faq_a1: 'Yes. You can upgrade to Pro or downgrade back to Free at any time from your Account Settings.',
    pricing_faq_q2: 'Do you support Open Banking?',
    pricing_faq_a2: "Not yet — Compass uses secure manual statement uploads (PDF/CSV) so we can support any Israeli or international institution from day one, without waiting on bank integrations.",
    pricing_faq_q3: 'Is my financial data secure?',
    pricing_faq_a3: 'All data is encrypted in transit and at rest, and protected by row-level security so only you can ever access your own accounts and transactions.',

    // About Page
    about_title: 'About Compass',
    about_subtitle: 'Compass is a personal finance management platform that gives you a unified, automated view of every account, statement, and transaction you have — without connecting your bank credentials to a third party.',
    about_mission_title: 'Our mission',
    about_mission_text: "We believe staying on top of your finances shouldn't require spreadsheets, multiple banking apps, or hours of manual reconciliation. Compass aggregates your financial documents in one place, automatically extracts transactions from uploaded statements using AI, and surfaces the insights that actually matter — so you can focus on decisions, not data entry.",
    about_feature_title: 'The killer feature: Smart Alerts Center',
    about_feature_subtitle: 'Proactive, not reactive',
    about_feature_text: "Most finance apps wait for you to go looking for problems. Compass's Alerts Center proactively flags unusual charges, duplicate billings, and savings opportunities the moment they're detected — so you find out before they cost you money, not after.",
    about_who_for_title: 'Who Compass is built for',
    about_persona_individual_title: 'Individual Consumer',
    about_persona_individual_text: 'Manages personal accounts and wants a clear, automated view of where their money goes each month.',
    about_persona_business_title: 'Small Business Owner',
    about_persona_business_text: 'Manages business accounts and needs duplicate-charge detection and tax-readiness without hiring a bookkeeper.',
    about_persona_investor_title: 'Pro Investor',
    about_persona_investor_text: 'Manages an investment portfolio and wants yield optimization alerts to spot underperforming cash.',
  },
  he: {
    dir: 'rtl',
    nav_home: 'בית',
    nav_about: 'אודות',
    nav_pricing: 'תמחור',
    nav_dashboard: 'לוח בקרה',
    nav_alerts: 'מרכז התראות',
    nav_statements: 'דפי חשבון',
    nav_portfolio: 'תיק השקעות',
    nav_settings: 'הגדרות חשבון',
    nav_insights: 'תובנות',
    nav_login: 'התחברות',
    nav_register: 'הרשמה',
    footer_about: 'אודות',
    footer_privacy: 'פרטיות',
    footer_terms: 'תנאים',
    footer_contact: 'צור קשר',
    footer_copyright: 'כל הזכויות שמורות.',

    // Privacy Page
    privacy_title: 'מדיניות פרטיות',
    privacy_subtitle: 'כיצד אנו אוספים, משתמשים ומגנים על המידע האישי שלכם.',
    privacy_collect_title: 'מידע שאנו אוספים',
    privacy_collect_body: 'אנו אוספים מידע שתספקו לנו ישירות, כגון שם, כתובת דוא"ל ונתוני חשבון פיננסי שתבחרו להעלות. כמו כן, אנו אוספים נתוני שימוש אוטומטית, כולל נתוני יומן, מידע על המכשיר וקובצי עוגיות.',
    privacy_use_title: 'כיצד אנו משתמשים במידע',
    privacy_use_body: 'אנו משתמשים במידע שנאסף כדי לספק, לתחזק ולשפר את שירותינו, לעבד עסקאות, לשלוח תקשורת שיווקית ועסקית, ולעמוד בדרישות החוק.',
    privacy_share_title: 'שיתוף מידע',
    privacy_share_body: 'אנו לא מוכרים את המידע האישי שלכם. אנו עשויים לשתף מידע עם ספקי שירות צד שלישי המסייעים בהפעלת הפלטפורמה, בכפוף להסכמי סודיות. כמו כן, אנו עשויים לגלות מידע כאשר הדבר נדרש על פי חוק.',
    privacy_security_title: 'אבטחת נתונים',
    privacy_security_body: 'אנו מיישמים אמצעי אבטחה תעשייתיים סטנדרטיים, כולל הצפנה בהעברה ובאחסון, בקרות גישה וביקורות אבטחה שוטפות. עם זאת, אף שיטת העברה דרך האינטרנט אינה מאובטחת לחלוטין.',
    privacy_contact_title: 'צרו קשר',
    privacy_contact_body: 'אם יש לכם שאלות לגבי מדיניות פרטיות זו, אנא צרו קשר בכתובת privacy@compass-finance.app.',
    privacy_updated: 'עדכון אחרון: 1 בינואר 2026',

    // Terms Page
    terms_title: 'תנאי שימוש',
    terms_subtitle: 'אנא קראו תנאים אלו בעיון לפני השימוש ב-Compass.',
    terms_acceptance_title: 'קבלת התנאים',
    terms_acceptance_body: 'בגישה לשירות Compass או בשימוש בו, אתם מסכימים להיות מחויבים לתנאי שירות אלה ולמדיניות הפרטיות שלנו. אם אינכם מסכימים לתנאים אלה, אנא אל תשתמשו בשירות.',
    terms_use_title: 'שימוש בשירות',
    terms_use_body: 'Compass היא פלטפורמה לניהול פיננסי אישי. תוכלו להשתמש בשירות שלנו למטרות חוקיות בלבד ובהתאם לתנאים אלה. אתם מתחייבים שלא לעשות שימוש לרעה בשירות.',
    terms_account_title: 'החשבון שלכם',
    terms_account_body: 'אתם אחראים לשמירה על אישורי הגישה לחשבונכם ועל כל הפעילות המתרחשת תחת חשבונכם. עליכם להודיע לנו מיד על כל שימוש לא מורשה בחשבונכם.',
    terms_liability_title: 'הגבלת אחריות',
    terms_liability_body: 'Compass מספקת כלי איסוף וניתוח נתונים פיננסיים למטרות מידע בלבד. איננו יועצים פיננסיים מורשים. השירות מסופק "כפי שהוא" ללא כל אחריות. לא נהיה אחראים לנזקים עקיפים, מקריים או תוצאתיים.',
    terms_changes_title: 'שינויים בתנאים',
    terms_changes_body: 'אנו שומרים לעצמנו את הזכות לשנות תנאים אלה בכל עת. נודיע לכם על שינויים מהותיים בדוא"ל או דרך הפלטפורמה. המשך השימוש בשירות לאחר שינויים מהווה קבלה של התנאים החדשים.',
    terms_updated: 'עדכון אחרון: 1 בינואר 2026',

    // Contact Page
    contact_title: 'צרו קשר',
    contact_subtitle: 'יש לכם שאלה או זקוקים לעזרה? נשמח לשמוע מכם.',
    contact_email_label: 'דוא"ל',
    contact_hours_label: 'שעות תמיכה',
    contact_hours_value: 'ראשון – חמישי, 09:00–18:00',
    contact_location_label: 'מיקום',
    contact_name_label: 'שם מלא',
    contact_name_placeholder: 'השם שלכם',
    contact_email_field_label: 'כתובת דוא"ל',
    contact_email_placeholder: 'you@example.com',
    contact_message_label: 'הודעה',
    contact_message_placeholder: 'איך נוכל לעזור לכם?',
    contact_submit: 'שלח הודעה',
    contact_success_title: 'ההודעה נשלחה!',
    contact_success_body: 'תודה שפניתם אלינו. נחזור אליכם תוך 1–2 ימי עסקים.',

    // User Menu
    usermenu_profile: 'פרופיל',
    usermenu_settings: 'הגדרות',
    usermenu_help: 'עזרה ותמיכה',
    usermenu_signout: 'התנתקות',
    usermenu_pro: 'מנוי פרו',
    usermenu_free: 'מסלול חינמי',
    usermenu_aria: 'תפריט משתמש',

    // Landing Page
    landing_title: 'דעו בדיוק לאן הולך הכסף שלכם.',
    landing_subtitle: 'העלו דף חשבון ותקבלו תובנות מיידיות מבוססות AI על ההוצאות שלכם — ללא חיבור לבנק.',
    landing_get_started: 'התחילו בחינם',
    landing_login: 'התחברות ללוח הבקרה',
    landing_stat_1_value: '+10,000',
    landing_stat_1_label: 'עסקאות שנותחו',
    landing_stat_2_value: '95%',
    landing_stat_2_label: 'דיוק סיווג',
    landing_stat_3_value: '< 2 דק\'',
    landing_stat_3_label: 'עד לתובנה הראשונה',
    landing_how_title: 'איך זה עובד',
    landing_how_1_title: 'העלו את הדף חשבון',
    landing_how_1_body: 'ייצאו PDF מהבנק והעלו אותו. ללא קישור חשבון, ללא שיתוף סיסמאות.',
    landing_how_2_title: 'ה-AI מחלץ הכל',
    landing_how_2_body: 'ה-AI שלנו קורא ומסווג כל עסקה — ספק, סכום, תאריך וסוג — אוטומטית.',
    landing_how_3_title: 'קבלו תובנות מיידיות',
    landing_how_3_body: 'ראו את מגמות ההוצאות, התראות חכמות וסיכום לפי קטגוריה — מיד.',
    landing_features_title: 'כל מה שצריך',
    landing_feat_1_title: 'לוח בקרה חכם',
    landing_feat_1_body: 'עקבו אחר היתרה הכוללת, שיעור החיסכון וההוצאות החודשיות עם כרטיסי KPI וגרפי מגמה.',
    landing_feat_2_title: 'התראות יזומות',
    landing_feat_2_body: 'קבלו התראות על חיובים חריגים, תשלומים כפולים והזדמנויות לחיסכון — לפני שיעלו לכם.',
    landing_feat_3_title: 'תובנות עמוקות',
    landing_feat_3_body: 'ניתוח הוצאות לפי קטגוריה, מגמות של 6 חודשים והרגלי הוצאות — מנוי Pro.',
    landing_pricing_title: 'תמחור פשוט ושקוף',
    landing_pricing_free_name: 'חינמי',
    landing_pricing_free_price: '₪0',
    landing_pricing_free_desc: 'מושלם להתחיל',
    landing_pricing_free_f1: 'חשבון בנק אחד',
    landing_pricing_free_f2: '3 העלאות דף חשבון',
    landing_pricing_free_f3: 'לוח בקרה והתראות',
    landing_pricing_pro_name: 'Pro',
    landing_pricing_pro_price: '₪39.90',
    landing_pricing_pro_period: '/ חודש',
    landing_pricing_pro_desc: 'לבהירות פיננסית אמיתית',
    landing_pricing_pro_f1: 'חשבונות ללא הגבלה',
    landing_pricing_pro_f2: 'העלאות ללא הגבלה',
    landing_pricing_pro_f3: 'תובנות AI ומגמות',
    landing_pricing_pro_f4: 'תמיכה מועדפת',
    landing_pricing_see_all: 'לעמוד התמחור המלא ←',
    landing_cta_title: 'מוכנים לשלוט בכספים שלכם?',
    landing_cta_subtitle: 'הצטרפו לאלפי משתמשים שסוף סוף מבינים לאן הכסף שלהם הולך.',
    landing_cta_button: 'התחילו בחינם',

    // Not Found Page
    notfound_title: 'הדף לא נמצא',
    notfound_subtitle: 'הדף שאתם מחפשים לא קיים או שהוסר.',
    notfound_return_home: 'חזרה לדף הבית',

    // Login Page
    login_heading: 'ברוכים השבים',
    login_subheading: 'התחברו כדי לנהל את תיק ההשקעות שלכם בבטחה.',
    login_google_redirecting: 'מעבירים אתכם…',
    login_google_continue: 'התחברות עם Google',
    login_or_email: 'או באמצעות אימייל',
    login_email_label: 'כתובת אימייל',
    login_password_label: 'סיסמה',
    login_forgot_password: 'שכחתם סיסמה?',
    login_signing_in: 'מתחברים…',
    login_sign_in: 'התחברות',
    login_no_account: 'אין לכם חשבון?',
    login_sign_up: 'הרשמה',
    login_fill_all_fields: 'נא למלא את כל השדות.',
    login_failed: 'ההתחברות נכשלה. בדקו את פרטי הכניסה.',
    login_google_failed: 'ההתחברות עם Google נכשלה.',
    trust_encrypted_connection: 'חיבור מוצפן',
    trust_secure_architecture: 'ארכיטקטורה מאובטחת',
    trust_enterprise_grade: 'איכות ארגונית',

    // Register Page
    register_heading: 'יצירת חשבון',
    register_subheading: 'התחילו לאתמט את הבינה הפיננסית שלכם.',
    register_google_signup: 'הרשמה עם Google',
    register_full_name_label: 'שם מלא',
    register_email_label: 'כתובת אימייל',
    register_password_label: 'סיסמה',
    register_confirm_password_label: 'אימות סיסמה',
    register_creating_account: 'יוצרים חשבון…',
    register_create_account: 'יצירת חשבון',
    register_have_account: 'יש לכם כבר חשבון?',
    register_log_in: 'התחברות',
    register_fill_all_fields: 'נא למלא את כל השדות.',
    register_passwords_mismatch: 'הסיסמאות אינן תואמות.',
    register_failed: 'יצירת החשבון נכשלה. בדקו אם מפתחות Supabase מוגדרים.',
    register_google_failed: 'ההרשמה עם Google נכשלה.',
    register_email_confirm_required: 'החשבון נוצר! נא לבדוק את תיבת האימייל לאימות החשבון לפני ההתחברות.',

    // Forgot Password Page
    forgot_heading: 'שכחתם סיסמה?',
    forgot_subheading: 'הזינו את כתובת האימייל שלכם ונשלח לכם קישור לאיפוס.',
    forgot_check_inbox: 'בדקו את תיבת הדואר — קישור לאיפוס נשלח אל',
    forgot_back_to_signin: 'חזרה להתחברות',
    forgot_email_label: 'כתובת אימייל',
    forgot_sending: 'שולחים…',
    forgot_send_reset_link: 'שליחת קישור לאיפוס',
    forgot_enter_email: 'נא להזין את כתובת האימייל שלכם.',
    forgot_send_failed: 'שליחת הקישור לאיפוס נכשלה.',

    // Dashboard sections
    dashboard_welcome_back: 'ברוכים השבים',
    dashboard_summary: 'הנה סיכום של התנועה הפיננסית שלכם.',
    dashboard_last_updated: 'עדכון אחרון',
    kpi_total_balance: 'יתרה כוללת',
    kpi_total_balance_tip: 'היתרה המצטברת בכל החשבונות המקושרים שלכם. האחוז מציג את שיעור הצמיחה הממוצע המשוקלל בין החשבונות.',
    kpi_savings: 'חיסכון',
    kpi_savings_tip: 'סך היתרה בחשבונות מסוג חיסכון.',
    kpi_monthly_expenses: 'הוצאות חודשיות',
    kpi_monthly_expenses_tip: 'סך עסקאות החיוב בחודש הקלנדרי הנוכחי. האחוז משווה לחודש הקודם.',
    quick_actions_title: 'פעולות מהירות',
    quick_action_upload_statement: 'העלאת דף חשבון',
    quick_action_view_transactions: 'צפייה בתנועות',
    quick_action_alerts_center: 'מרכז התראות',
    quick_action_drop_zone: 'גררו ושמטו מסמכים כאן',
    recent_tx_title: 'תנועות אחרונות',
    recent_tx_filter: 'סינון',
    recent_tx_more_options: 'אפשרויות נוספות',
    recent_tx_col_transaction: 'תנועה',
    recent_tx_col_date: 'תאריך',
    recent_tx_col_status: 'סטטוס',
    recent_tx_col_amount: 'סכום',
    recent_tx_none: 'אין תנועות אחרונות',
    tx_status_completed: 'הושלם',
    tx_status_pending: 'בהמתנה',
    tx_status_failed: 'נכשל',
    chart_spending_trends: 'מגמות הוצאות',
    chart_view_details: 'הצגת פרטים',
    chart_empty_state: 'אין נתוני הוצאות עדיין. העלו דף חשבון כדי לראות את המגמות שלכם כאן.',
    chart_subtitle: 'הוצאות חודשיות',
    chart_total_label: 'סך הכול',
    chart_months: 'חודשים',
    chart_monthly_avg: 'ממוצע חודשי',
    chart_peak_month: 'חודש שיא',
    chart_legend_current: 'חודש נוכחי',
    chart_legend_above: 'מעל הממוצע',
    chart_legend_below: 'מתחת לממוצע',

    // Month abbreviations
    month_jan: 'ינו', month_feb: 'פבר', month_mar: 'מרץ', month_apr: 'אפר',
    month_may: 'מאי', month_jun: 'יוני', month_jul: 'יולי', month_aug: 'אוג',
    month_sep: 'ספט', month_oct: 'אוק', month_nov: 'נוב', month_dec: 'דצמ',

    // Category names
    cat_bills_utilities: 'חשבונות ושירותים',
    cat_food_dining: 'אוכל ומסעדות',
    cat_shopping: 'קניות',
    cat_transportation: 'תחבורה',
    cat_health: 'בריאות',
    cat_entertainment: 'בידור',
    cat_electronics: 'אלקטרוניקה',
    cat_other: 'אחר',
    cat_uncategorized: 'לא מקוטלג',

    // Transactions Page
    tx_page_title: 'תנועות',
    tx_page_total: 'תנועות בסך הכול',
    tx_search_placeholder: 'חיפוש לפי בית עסק או קטגוריה…',
    tx_filter_all: 'הכול',
    tx_filter_expenses: 'הוצאות',
    tx_filter_income: 'הכנסות',
    tx_load_failed: 'טעינת התנועות נכשלה',
    tx_no_match: 'אין תנועות התואמות את הסינון שלכם.',

    // Alerts Page
    alerts_page_title: 'מרכז התראות',
    alerts_page_subtitle: 'מעקב וניהול של התראות חשבון קריטיות, הזדמנויות לאופטימיזציה ואירועי אבטחה הדורשים את תשומת לבכם.',
    alerts_system_status: 'מצב המערכת:',
    alerts_status_optimal: 'תקין',
    alerts_stat_new: 'התראות חדשות',
    alerts_stat_new_attention: 'דורשות תשומת לב',
    alerts_stat_all_clear: 'הכול תקין',
    alerts_stat_in_progress: 'בטיפול',
    alerts_stat_pending_resolution: 'בהמתנה לפתרון',
    alerts_stat_saved: 'נשמרו למועד אחר',
    alerts_stat_archived: 'משימות בארכיון',
    alerts_stat_value_impact: 'השפעה כספית משוערת',
    alerts_stat_from_optimization: 'מהתראות אופטימיזציה',
    alerts_filter_all: 'כל ההתראות',
    alerts_filter_critical: 'קריטי',
    alerts_filter_opportunities: 'הזדמנויות',
    alerts_filter_duplicates: 'כפילויות',
    alerts_sort_by_priority: 'מיון לפי: עדיפות',
    alerts_review: 'בדיקה',
    alerts_dismiss: 'התעלמות',
    alerts_dismiss_aria: 'התעלמות מהתראה',
    alerts_none_in_category: 'אין התראות בקטגוריה זו.',
    pagination_previous: 'עמוד קודם',
    pagination_next: 'עמוד הבא',

    // Upload Page
    upload_page_title: 'העלאה מאובטחת',
    upload_page_subtitle: 'שלחו את המסמכים הפיננסיים שלכם לעיבוד ואחסון מאובטחים בעזרת בינה מלאכותית.',
    upload_cancel: 'ביטול העלאה',
    upload_step_choose_type: 'בחירת סוג',
    upload_step_upload_file: 'העלאת קובץ',
    upload_step_preview: 'תצוגה מקדימה',
    upload_step_review_save: 'בדיקה ושמירה',
    upload_no_accounts: 'אין לכם חשבונות עדיין. הוסיפו חשבון כדי להמשיך.',
    upload_institution_label: 'מוסד פיננסי',
    upload_select_institution: 'בחרו מוסד…',
    upload_account_name_label: 'שם החשבון',
    upload_account_name_placeholder: 'לדוגמה: חשבון עו"ש אישי',
    upload_account_type_label: 'סוג חשבון',
    upload_adding: 'מוסיפים…',
    upload_add_account: 'הוספת חשבון',
    upload_account_label: 'חשבון',
    upload_select_account: 'בחרו חשבון…',
    upload_doc_type_label: '1. סוג מסמך',
    doc_type_bank_title: 'דף חשבון בנק',
    doc_type_bank_desc: 'סיכומי חשבון חודשיים',
    doc_type_tax_title: 'מסמך מס',
    doc_type_tax_desc: 'דוחות וטפסי מס',
    doc_type_invoice_title: 'חשבונית',
    doc_type_invoice_desc: 'חשבונות מספקים או לקוחות',
    doc_type_other_title: 'אחר',
    doc_type_other_desc: 'חוזים והודעות',
    upload_file_label: '3. העלאת קובץ',
    upload_drag_drop: 'גררו ושמטו את הקובץ כאן',
    upload_or_browse: 'או לחצו לבחירה מהמחשב',
    upload_click_replace: 'לחצו להחלפה',
    upload_max_size: 'מקסימום 50MB',
    upload_parsing_pdf: 'מנתחים את ה-PDF…',
    upload_no_tx_found: 'לא נמצאו תנועות בקובץ ה-PDF. אפשר שהפורמט עדיין לא נתמך.',
    upload_parse_failed: 'ניתוח ה-PDF נכשל:',
    upload_parsed_tx_title: 'תנועות שחולצו',
    upload_selected_for_import: 'מתוך {total} נבחרו לייבוא',
    upload_col_date: 'תאריך',
    upload_col_description: 'תיאור',
    upload_col_category: 'קטגוריה',
    upload_col_amount: 'סכום',
    upload_import_failed: 'הייבוא נכשל',
    upload_import_complete: 'הייבוא הושלם',
    upload_imported_success: 'תנועות יובאו בהצלחה.',
    upload_duplicates_skipped: 'כפילויות דולגו.',
    upload_view_transactions: 'צפייה בתנועות',
    upload_tips_title: 'טיפים לחילוץ נתונים בעזרת AI',
    upload_tips_intro: 'מנגנון ה-AI של Compass מחלץ באופן אוטומטי את נתוני התנועות. עקבו אחר ההנחיות הבאות לדיוק מושלם.',
    upload_tip_1: 'הקפידו שכל עמודי המסמך כלולים בקובץ אחד.',
    upload_tip_2: 'הסריקות צריכות להיות ישרות, מוארות היטב וקריאות ללא חיתוך.',
    upload_tip_3: 'הסירו הגנת סיסמה מקבצי PDF לפני ההעלאה.',
    upload_encrypted_transfer: 'העברה מוצפנת מקצה לקצה',
    upload_cancel_action: 'ביטול',
    upload_continue_to_review: 'המשך לבדיקה',
    upload_parse_pdf: 'ניתוח PDF',
    upload_saving: 'שומרים…',
    upload_import_n_transactions: 'ייבוא {count} תנועות',
    upload_institution_select_label: '2. מוסד פיננסי',
    upload_select_institution_placeholder: 'בחרו מוסד...',
    upload_parsing_csv: 'קוראים את הקובץ…',
    upload_parse_csv: 'המשך למיפוי עמודות',
    upload_map_columns: 'אישור מיפוי',
    upload_step_map_columns: 'מיפוי עמודות',
    upload_no_tx_found_csv: 'לא נמצאו שורות תקינות לאחר המיפוי. בדקו את הגדרות העמודות.',

    upload_method_label: 'שיטת ייבוא',
    upload_method_pdf_title: 'דף חשבון PDF',
    upload_method_pdf_desc: 'ייצוא PDF מהבנק או כרטיס האשראי',
    upload_method_csv_title: 'CSV / Excel',
    upload_method_csv_desc: 'ייצוא גיליון אלקטרוני מהבנק',

    csv_map_title: 'מיפוי עמודות',
    csv_map_subtitle: 'בחרו לאיזה שדה של Compass מתאימה כל עמודה בקובץ. עשינו ניחוש — תתקנו אם צריך.',
    csv_map_missing_fields: 'שדות חובה חסרים',
    csv_map_col_your_column: 'העמודה שלכם',
    csv_map_col_sample: 'דוגמה',
    csv_map_col_maps_to: 'ממופה ל',
    csv_map_skip: '— דלג על עמודה זו —',
    csv_field_date: 'תאריך',
    csv_field_amount: 'סכום',
    csv_field_description: 'תיאור',
    csv_field_direction: 'כיוון (אופציונלי)',

    // Insights Page
    insights_title: 'תובנות',
    insights_subtitle: 'פירוט של דפוסי ההוצאה שלכם.',
    insights_total_spent: 'סך ההוצאות',
    insights_transactions_count: 'תנועות',
    insights_total_income: 'סך ההכנסות',
    insights_avg_transaction: 'תנועה ממוצעת',
    insights_top_category: 'קטגוריה מובילה',
    insights_spending_by_category: 'הוצאות לפי קטגוריה',

    // Profile Page
    profile_title: 'פרופיל',
    profile_subtitle: 'ניהול הפרטים האישיים שלכם.',
    profile_display_name_label: 'שם תצוגה',
    profile_display_name_placeholder: 'השם המלא שלכם',
    profile_first_name_label: 'שם פרטי',
    profile_first_name_placeholder: 'שם פרטי בלבד',
    profile_email_label: 'אימייל',
    profile_save_success: 'הפרופיל נשמר בהצלחה.',
    profile_save_failed: 'שמירת הפרופיל נכשלה.',
    profile_saving: 'שומרים…',
    profile_save_changes: 'שמירת שינויים',
    profile_tier_free: 'חינמי',

    // Settings Page
    settings_title: 'הגדרות',
    settings_subtitle: 'ניהול ההעדפות והאבטחה של החשבון שלכם.',
    settings_section_display: 'תצוגה',
    settings_currency_label: 'מטבע',
    settings_currency_desc: 'בחרו כיצד הסכומים יוצגו באפליקציה.',
    settings_section_notifications: 'התראות',
    settings_email_alerts_label: 'התראות אימייל',
    settings_email_alerts_desc: 'קבלו סיכומי תנועות והתראות באימייל.',
    settings_push_alerts_label: 'התראות דחיפה',
    settings_push_alerts_desc: 'קבלו התראות בזמן אמת על המכשיר שלכם.',
    settings_section_security: 'אבטחה',
    settings_new_password_label: 'סיסמה חדשה',
    settings_confirm_password_label: 'אימות סיסמה חדשה',
    settings_password_updated: 'הסיסמה עודכנה בהצלחה.',
    settings_updating: 'מעדכנים…',
    settings_update_password: 'עדכון סיסמה',
    settings_passwords_mismatch: 'הסיסמאות אינן תואמות.',
    settings_password_too_short: 'הסיסמה צריכה להיות באורך 8 תווים לפחות.',
    settings_password_update_failed: 'עדכון הסיסמה נכשל.',
    settings_section_danger: 'אזור מסוכן',
    settings_delete_account_label: 'מחיקת חשבון',
    settings_delete_account_desc: 'מחיקה לצמיתות של חשבון ה-Compass שלכם וכל המידע הנלווה. פעולה זו אינה הפיכה.',
    settings_delete_account_btn: 'מחיקת חשבון',
    settings_delete_modal_title: 'מחיקת חשבון',
    settings_delete_modal_body: 'פעולה זו היא קבועה. כל המידע שלכם יימחק ולא ניתן לשחזור. נא לפנות לתמיכה כדי להמשיך במחיקת החשבון.',
    settings_cancel: 'ביטול',

    // Pricing Page
    pricing_title: 'תמחור פשוט ושקוף',
    pricing_subtitle: 'התחילו בחינם, שדרגו כשתצטרכו יותר.',
    pricing_most_popular: 'הפופולרי ביותר',
    pricing_free_name: 'חינמי',
    pricing_free_feature_1: 'עד 2 חשבונות מקושרים',
    pricing_free_feature_2: '5 העלאות דפי חשבון בחודש',
    pricing_free_feature_3: 'התראות בסיסיות (חיובים חריגים, כפילויות)',
    pricing_free_feature_4: 'מדדי לוח בקרה ומגמות הוצאה',
    pricing_free_cta: 'התחילו כאן',
    pricing_pro_name: 'Compass Pro',
    pricing_pro_feature_1: 'חשבונות והעלאות דפי חשבון ללא הגבלה',
    pricing_pro_feature_2: 'התראות אופטימיזציית תשואה',
    pricing_pro_feature_3: 'יצירת קטגוריות מותאמות אישית',
    pricing_pro_feature_4: 'מיזוג בתי עסק לאיתור כפילויות',
    pricing_pro_feature_5: 'אנליטיקה ותובנות מתקדמות',
    pricing_pro_cta: 'שדרוג ל-Pro',
    pricing_period_month: '/ לחודש',
    pricing_faq_title: 'שאלות נפוצות',
    pricing_faq_q1: 'אפשר להחליף תוכנית בהמשך?',
    pricing_faq_a1: 'כן. ניתן לשדרג ל-Pro או לחזור לתוכנית החינמית בכל עת מתוך הגדרות החשבון.',
    pricing_faq_q2: 'האם יש תמיכה ב-Open Banking?',
    pricing_faq_a2: 'עדיין לא — Compass משתמשת בהעלאת דפי חשבון מאובטחת באופן ידני (PDF/CSV) כדי שנוכל לתמוך בכל מוסד ישראלי או בין-לאומי מהיום הראשון, בלי להמתין לאינטגרציות עם בנקים.',
    pricing_faq_q3: 'האם המידע הפיננסי שלי מאובטח?',
    pricing_faq_a3: 'כל המידע מוצפן בהעברה ובאחסון, ומוגן באמצעות אבטחה בשורת נתונים כך שרק אתם יכולים לגשת לחשבונות ולתנועות שלכם.',

    // About Page
    about_title: 'אודות Compass',
    about_subtitle: 'Compass היא פלטפורמה לניהול פיננסי אישי המעניקה לכם תצוגה מאוחדת ואוטומטית של כל חשבון, דף חשבון ותנועה שיש לכם — בלי לחבר את פרטי הבנק שלכם לצד שלישי.',
    about_mission_title: 'המשימה שלנו',
    about_mission_text: 'אנחנו מאמינים שלהישאר עם יד על הדופק הפיננסי לא צריך לדרוש גיליונות אלקטרוניים, מספר אפליקציות בנקאות, או שעות של התאמה ידנית. Compass מאגדת את המסמכים הפיננסיים שלכם במקום אחד, מחלצת באופן אוטומטי תנועות מדפי חשבון שהועלו בעזרת בינה מלאכותית, ומציגה את התובנות החשובות באמת — כדי שתוכלו להתמקד בהחלטות, לא בהזנת נתונים.',
    about_feature_title: 'התכונה הבולטת: מרכז התראות חכם',
    about_feature_subtitle: 'יזום, לא תגובתי',
    about_feature_text: 'רוב אפליקציות הפיננסים מחכות שתחפשו בעיות בעצמכם. מרכז ההתראות של Compass מסמן באופן יזום חיובים חריגים, חיובים כפולים והזדמנויות לחיסכון בו ברגע שהם מתגלים — כך שתדעו לפני שהם עולים לכם בכסף, ולא אחרי.',
    about_who_for_title: 'למי Compass מתאימה',
    about_persona_individual_title: 'צרכן פרטי',
    about_persona_individual_text: 'מנהל חשבונות אישיים ומעוניין בתצוגה ברורה ואוטומטית של לאן הכסף שלו הולך בכל חודש.',
    about_persona_business_title: 'בעל עסק קטן',
    about_persona_business_text: 'מנהל חשבונות עסקיים וזקוק לאיתור חיובים כפולים ולמוכנות לדיווחי מס בלי להעסיק מנהל חשבונות.',
    about_persona_investor_title: 'משקיע מקצועי',
    about_persona_investor_text: 'מנהל תיק השקעות ומעוניין בהתראות אופטימיזציית תשואה לאיתור כסף שאינו מניב תשואה מספקת.',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem(STORAGE_KEY) || 'en'
  })

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language)
    document.documentElement.lang = language
    document.documentElement.dir = TRANSLATIONS[language].dir
  }, [language])

  function t(key) {
    return TRANSLATIONS[language][key] ?? key
  }

  // Translate a category name from DB (e.g. "Bills & Utilities" → key cat_bills_utilities)
  function tCat(name) {
    const key = 'cat_' + (name || 'uncategorized')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '_')
      .replace(/^_|_$/g, '')
    return TRANSLATIONS[language][key] ?? name ?? t('cat_uncategorized')
  }

  // Translate a 3-letter English month abbreviation (e.g. "Jan" → "ינו")
  function tMonth(abbr) {
    const key = 'month_' + abbr.toLowerCase().substring(0, 3)
    return TRANSLATIONS[language][key] ?? abbr
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, dir: TRANSLATIONS[language].dir, t, tCat, tMonth }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within a LanguageProvider')
  return ctx
}
